site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/AccenturePrithvi/backstage
edit_uri: edit/master/docs

plugins:
  - techdocs-core

nav:
  - VWDocs:
    - Welcome to VW: 'vwdocs/welcome-to-VW.AC.md'
    - Cars: 'vwdocs/concepts-vehicles-and-devices.md'
